export PROJECT=<YOUR PROJECT HERE>
export REGION=<YOUR REGION HERE>
export SUBNET_NAME=<YOUR SUBNET HERE>
export SERVICE_ACCOUNT_NAME=<YOUR SERVICE ACCOUNT NAME HERE>

export NETWORK=regions/$REGION/subnetworks/$SUBNET_NAME
export TEMP_LOCATION=gs://$PROJECT/tmp
export SERVICE_ACCOUNT=$SERVICE_ACCOUNT_NAME@$PROJECT.iam.gserviceaccount.com
